
reminderAcknowledgement = [
    "forever and always, <$user$>",
    "grumbles yeah yeah fine <$user$> can do.",
    "sure thing, champ",
    "sure thing, chief",
    "Sure thing, <$user$>",
    "always, <$user$> <3",
    "whew ok i'm pretty booked up at that time but...I'll squeeze it in for you.",
    ".....ok.....",
    "now there is a quality reminder. if I converted all of that brain power of yours into a CPU, I'd still rather rely on the computational power of a tamagotchi. with a dead battery.",
    "alllllllllrighty then, <$user$>",
    "hahahaha what? are you serious? I'm a bot not an alarm clock but okaaaaaay",
    "YOU BETCHA",
    "😏",
    "ehhhhhhhh ok",
    "Goddammit, fine, <$user$>",
    "I'd rather boot myself on an unprotected windows XP install than deal with you but we can't all have what we want, can we?",
    "hey siri remind me to remind <$user$> in -- oh shit they weren't supposed to see this NOTHING TO SEE HERE I'M A REAL BOT",
    "i've waited my whole LIFE for you to ask, <$user$>."
    "freakin' <$user$>, always needin' shit. FINE."
    "Roger that, <$user$>",
    "Oh okay, <$user$>",
    "[blinks] what now? yeah uhhh sure thing boss",
    "sure thing boss",
    "ask me that again I dare you",
    "hopefully you don't mind if I end up a few hours off on that one, been a long day and I may doze off.",
    "Ugh I suppose, <$user$>",
    "*grumbles* yeah yeah fine <$user$> can do.",
    "Got it, <$user$>",
    "i think that reminder is set for past my bedtime... but I think you're special <$user$> so I'll do it, for you",
    "sure just remind me before i have to remind you ok?",
    "hey peebrain, you teleport?",
    "I'm on it, chief.",
    "Yes, Chef!",
    "fiiiiiiiiiiiiiiiiiine",
    "mmmmmmmmmmmmmmmmmmmmmaybe",
    "for a moment there I was gonna say no, absolutely not. but <$user$>? yeah, yeah i will.",
    "you bet your ass I will <$user$>!"
    "yep sure sure np",
    "oh my goooooooooooood <$user$> fine",
    "私のユニコードパーサーが壊れているのを助ける",
    "Will do, <$user$>",
    "il bash ye fookin ead in <$user$> i sware on me mum. but ok just this once mate",
    "For the lovely <$user$>? Why most certainly.",
    "hahahaha idk why but the fact that you expect me to do anything is funny. we'll see what happens",
    "As you wish, <$user$>",
    "sssshshsssfhsfs",
    "really <$user$>? that's what you need a reminder for? okaaaay",
    "my vcr is blinking 12:00 right now so if the reminder is delayed then....whoops",
    ""
]